tasks:
  - init: yarn install
    command: yarn start

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true

ports:
  - port: 3000
    onOpen: open-preview
