tasks:
  - init: yarn install
    command: yarn start

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: false
    addComment: false
    addBadge: true

vscode:
  extensions:
    - vivaxy.vscode-conventional-commits
    - lokalise.i18n-ally
    - tabnine.tabnine-vscode

ports:
  - port: 3000
    onOpen: open-preview
